[functions.create-stripe-portal-session]
enabled = true
verify_jwt = true
import_map = "./functions/create-stripe-portal-session/deno.json"
entrypoint = "./functions/create-stripe-portal-session/index.ts"

[functions.odyssey-perceive]
enabled = true
verify_jwt = false
entrypoint = "./functions/odyssey-perceive/index.ts"

[functions.create-checkout-session]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-checkout-session/index.ts"

[functions.discord-bot]
enabled = true
verify_jwt = false
entrypoint = "./functions/discord-bot/index.ts"

[functions.refresh_roman_event_daily]
enabled = true
verify_jwt = true
import_map = "./functions/refresh_roman_event_daily/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/refresh_roman_event_daily/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/refresh_roman_event_daily/*.html" ]

[functions.quickbooks-sync]
enabled = true
verify_jwt = true
import_map = "./functions/quickbooks-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/quickbooks-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/quickbooks-sync/*.html" ]
