[functions.create-stripe-portal-session]
enabled = true
verify_jwt = true
import_map = "./functions/create-stripe-portal-session/deno.json"
entrypoint = "./functions/create-stripe-portal-session/index.ts"

[functions.odyssey-perceive]
enabled = true
verify_jwt = false
entrypoint = "./functions/odyssey-perceive/index.ts"

[functions.create-checkout-session]
enabled = true
verify_jwt = false
entrypoint = "./functions/create-checkout-session/index.ts"

[functions.discord-bot]
enabled = true
verify_jwt = false
entrypoint = "./functions/discord-bot/index.ts"
